### ISSUE TITLE
Solving "Virtuoso 22023 Error SR353: Sorted TOP clause specifies more then 11000 rows to sort." error

### ISSUE THREAD

**Issue by jplu** [silk-framework/silk#31]
Hi,

In order to solve this Virtuoso error which happen pretty often as Virtuoso by default fix this number to 10000, changing the way how Silk creates the queries could be a solution. For example changing :

```
SELECT ?a ?v0
FROM <http://dbpedia.org>
WHERE
  {
    ?a a <http://dbpedia.org/ontology/Country> .
    OPTIONAL
    {
        ?a <http://www.w3.org/2000/01/rdf-schema#label> ?v0 .
    }
  }
OFFSET  10000
LIMIT   1000
```

To

```
SELECT ?a ?v0
WHERE
  {
    {
      SELECT ?a ?v0
      FROM <http://dbpedia.org>
      WHERE
        {
          ?a a <http://dbpedia.org/ontology/Country> .
          OPTIONAL
          {
            ?a <http://www.w3.org/2000/01/rdf-schema#label> ?v0 .
          }
        } 
    }
  }
OFFSET 10000
LIMIT 1000
```

No ?

**Comment by jindrichmynarz** [comment]
You would need an `ORDER BY` clause to maintain stable sort order, so that you page through result bindings with `LIMIT`/`OFFSET` reliably. Additionally, `FROM` is not allowed in sub-queries (see the [specification](http://www.w3.org/TR/sparql11-query/#rSubSelect)), so it would be better to use `GRAPH`. Your query would change to the following one:

```
SELECT ?a ?v0
WHERE
  {
    {
      SELECT ?a ?v0
      WHERE {
        GRAPH <http://dbpedia.org> {
          ?a a <http://dbpedia.org/ontology/Country> .
          OPTIONAL {
            ?a <http://www.w3.org/2000/01/rdf-schema#label> ?v0 .
          }
        }
      }
      ORDER BY ?a ?v0 
    }
  }
OFFSET 10000
LIMIT 1000
```

In general, I strongly agree that the issue of Virtuoso's [scrollable cursors](http://docs.openlinksw.com/virtuoso/rdfsparql.html#rdfsparqlimplementationextentadvices) (section "Example: Prevent Limits of Sorted LIMIT/OFFSET query")) should be addressed in Silk.
