### ISSUE TITLE
Multiple values of the same property

### ISSUE THREAD

**Issue by skarampatakis** [silk-framework/silk#71]
Hi, I have the same issue as described here

https://groups.google.com/forum/#!searchin/silk-discussion/set|sort:relevance/silk-discussion/pYrmKyYj2Oc/lUfR1DEokiAJ

However this behaviour, drives into linkage rule failure. On our dataset we have instances where an instance may have mutliple values for a single property, but a language tag is not present to have a filter. An example is shown below.
![default](https://cloud.githubusercontent.com/assets/2419820/19588604/89247ee4-976f-11e6-8ced-f387e8818b51.PNG)

This two entities are the same so they we should create a link, but because of the mentioned behaviour Silk fails to match them. Is there anything we can do to tackle this? I am using Silk 2.7.1. Thank you in advance.

**Comment by afeliachi** [comment]
Hi,
What is the threshold that you gave to your Dice coefficient?

**Comment by skarampatakis** [comment]
0.3 I think. If I increase it, silk actually make the match but also introduce wrong links elsewhere. I overcame this issue by renaming the entities, adding a suffix and then revert the change. But I believe it is a wrong behaviour.

**Comment by afeliachi** [comment]
I think using the tokenization transformation is the source of the issue here. The tokenizer will results one set of tokens that are independant from your input values.
I suggest to use the TokenwiseStringDistance. This take each input value separately  and tokenize  it just before applying the chosen distance measure. It worked for me just fine in similar cases.

Cheers

**Comment by skarampatakis** [comment]
Hi,
Haven't tested it as you suggested yet. Although it sounds reasonable. Will inform when I find some time... Thx!
